INSERT INTO [DBO].[Schools](EduId, Name, Country, City, Address)
VALUES ('031603','Neumann János Középiskola','Hungary','Eger','Rákóczi út 48.'),
	   ('15823443206','Kiss ferenc Erdészeti Technikum','Hungary','Szeged','József Attila tér 6721.'),
	   ('120606','Kőrösi Csoma Sándor Gimnázium, Szakközép-, Szakképző Iskola és Kollégium','Hungary','Hajdúnánás','Bocskai utca 29.'),
	   ('FI 80798','Eötvös Loránd University','Hungary','Budapest','Egyetem tér 1-3.'),
	   ('FI 23344','Budapest University of Technology and Economics','Hungary','Budapest','Műegyetem rkp. 3.'),
	   ('CZ 12345','University of New York in Prague','Chechia','Praha','Londýnská 41'),
	   ('FR 12322','Ecole Maternelle Publique, RPI','France','Longchamp','2 Place Deleglise'),
	   ('CH 23444','KV Luzern Berufsakademie / Höhere Fachschule für Wirtschaft, Marketing und Wirtschaftsinformatik','Schweiz','Luzern','Dreilindenstrasse 20'),
	   ('AT 22222','Pädagogische Hochschule Steiermark Graz','Austria','Graz','Hasnerplatz 12'),
	   ('UK 11223','Camphill School Aberdeen','United Kingdom','Aberdeen','Murtle House, Bieldside, AB15 9EP'),
	   ('UK 22555','Stranraer Academy','United Kingdom','Stranraer','McMasters Road, DG9 8BY'),
	   ('PL 00992','Szkoła Języków i Zarządzania Nauczycielskie Kolegium Języków Obcych PROMAR','Poland','Rzeszów','Bohaterów 12'),
	   ('IT 10200','CAVOUR','Italy','Firenze','V.LE Machiavelli, 31-33'),
	   ('IT 11340','Centro Scolastico Dante Alighieri','Italy','Quarto','Via Campana 383'),
	   ('01131710376','ALMA MATER STUDIORUM - Università di Bologna','Italy','Bologna','Via Zamboni, 33'),
	   ('OX1 2JD','University of Oxford','United Kingdom','Oxford','Wellington Square'),
	   ('BS 11000','University of Basel','Schweiz','Basel','Petersplatz 1');